### ISSUE TITLE
Trial of Style Instance Error

### ISSUE THREAD

**Issue by mdon3153** [fstenstrom/world-boss-timers#104]
When in the Trial of Style Instance and hover the mouse over the Transmogrifier get the following error:

Message: Interface/AddOns/WorldBossTimers/WorldBossTimers.lua:230: table index is nil

Time: Thu Aug  3 09:14:47 2023

Count: 2

Stack: Interface/AddOns/WorldBossTimers/WorldBossTimers.lua:230: table index is nil

Locals:

**Comment by fstenstrom** [comment]
The Trial of Style event has ended, so I'll have to look into this the next time it's available: 20th of March 2024.

**Comment by fstenstrom** [comment]
Most likely fixed by #107

**Comment by fstenstrom** [comment]
Missed to check this while Trial of Style was active. Assuming it's fixed. Please reopen if not.
