### ISSUE TITLE
Leading zeros can break sharing

### ISSUE THREAD

**Issue by Kanegasi** [fstenstrom/world-boss-timers#106]
If your WBT has seen a higher instance id, such as 12345, and someone shares a timer with a lower id, such as:

`💀Oondasta💀: 5m (WorldBossTimers:1696299766-678)`

Your WBT will not recognize the share, since your WBT is tracking 00678, not 678.

**Comment by fstenstrom** [comment]
I can't replicate. I don't think the leading zeros are an issue, the addon just adds them to the timer window to try to visually align the timers.

**Comment by fstenstrom** [comment]
Most likely fixed in 6a16c96a6c3882398cd2b420134bf41e7b76d27c.

Bug happened when sharing (well, receiving) a new timer when the player already had an **expired** one for the current shard for that boss. (The bug was likely introduced when fixing support for sharding.)
