### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by mandynicole5** [fstenstrom/world-boss-timers#110]
/wbt stopped working for me earlier today, not able to view or share timers, uninstalling and reinstalling did not work, reloading did not work

**Comment by fstenstrom** [comment]
I'd probably need stacktrace (e.g. from Bugsack+Buggrabber) to understand this. Could also be interface mismatch. Closing for now since it's been a while. If you have stacktrace please reopen.

**Comment by fstenstrom** [comment]
This could be caused by #109
