### ISSUE TITLE
Addon casuses framerate drops

### ISSUE THREAD

**Issue by firebellys** [fstenstrom/world-boss-timers#121]
In war within, I'm noticing a frame drop when using the addon, every other second the rendering stutters. It's steady and easily reproducible by enabling and disabling the addon. Happens every second or two from what i see. Very noticeable on mount animations, they pause every second or so.

**Comment by fstenstrom** [comment]
I can't reproduce this.

- Does it happen only in certain zones?
- Does it happen if you disable all addons but WBT?
- If you close the window with the timers, does it make any difference?

**Comment by firebellys** [comment]
- Zone doesn't matter
- Still happens, it's not impacted by other addons
- Window Open Only, closed it's ok.

**Comment by fstenstrom** [comment]
Thanks. Some follow up:

- Do you get any lua errors? If so, what does it say? You can turn on/off errors with `/console scriptErrors 1`
- If you run `/wbt reset` (try first after checking if you get lua errors), does that make any difference?

**Comment by fstenstrom** [comment]
Also, I'm assuming you're using latest version (v1.12.12)?

**Comment by firebellys** [comment]
- No Errors seen after console is on
- Resetting timers **FIXED IT**
- Using the latest (use Curseforge every day)

Fixed now!

**Comment by fstenstrom** [comment]
Good that it's fixed for you, and thanks for reporting the issue.

And yes, it's something related to old data. There is already a step during addon initializtion which removes all old timers if the new addon version has made changes to the timer data structure, but that's a flag that's set manually for each version if there were such changes. I don't recall any such changes lately, but may have missed something.

I'll leave this issue open for now, and I'll probably make a coming version reset all old timers.

**Comment by fstenstrom** [comment]
Looked a bit more at this, and seems to be a scaling issue. At about 500 timers I can also notice the FPS drop every second. I'll add a step which removes timers more than a day old or so.
