### ISSUE TITLE
SendChatMessage not working anymore

### ISSUE THREAD

**Issue by hollo6** [fstenstrom/world-boss-timers#35]
It seems Blizzard stealth broke the SendChatMessage function in 8.2.5:

Message: Warning: AddOn WorldBossTimers attempted to call a protected function (UNKNOWN()) which may require interaction.
Debug:
   [C]: ?
   [C]: SendChatMessage()
   WorldBossTimers\WorldBossTimers.lua:236:
      WorldBossTimers\WorldBossTimers.lua:235
   WorldBossTimers\WorldBossTimers.lua:397:
      WorldBossTimers\WorldBossTimers.lua:388

Emote still works.
Maybe it's worth considering using emote or a hidden addon communication channel.

The only sensible thread I could find about this:
https://us.forums.blizzard.com/en/wow/t/macroeditbox-weird-problem-after-8-2-5/319290/8

**Comment by fstenstrom** [comment]
Thanks, I'll take a look at emote in 8.3. I just guess that if it works, it's considered to be a workaround that blizz forgot to disable.

Hidden addon communication only works for guild/party/raid/same-realm :(
