### ISSUE TITLE
Manually (re)set a timer

### ISSUE THREAD

**Issue by fstenstrom** [fstenstrom/world-boss-timers#41]
People sometimes see when a boss is pulled by the zone-wide yell, but don't make it in time to see the boss die (which happens in ~5 sec). This can allow them to still get a timer.

**Comment by TheCheat54** [comment]
To be honest this could be taken further by parsing chat events for boss deaths. Nalak and Galleon in particular have zone-wide announcements for their spawn and Nalak has a zone-wide announce for his death that could be used for the timer. Galleon's example where there isn't a zone-wide announce for his death could just start the timer at his spawn and add 6 seconds.

**Comment by fstenstrom** [comment]
Closing in favor of parsing zone-wide death announcements. See #89
