### ISSUE TITLE
Can you support multi server statistics

### ISSUE THREAD

**Issue by xiewl** [fstenstrom/world-boss-timers#42]

**Comment by fstenstrom** [comment]
Multiple servers can be tracked at the same time (don't remember if it's enabled by default though). This is for individual use only though, since sharing them efficiently would require knowing what servers are connected.

Could you describe your use case?

**Comment by xiewl** [comment]
Sorry, I didn't make it clear
I mean to see all the time on one page which helps me switch servers

**Comment by fstenstrom** [comment]
Do you have the "Multi-realm + Warmode" option enabled? You can enable it through GUI or toggle it with `/wbt multi`. This should show all servers you have seen a kill on, or am I missing something?

**Comment by xiewl** [comment]
I have not，Maybe my plugin version is too old

**Comment by xiewl** [comment]
I updated plugin, it's work，thanks a lot
