### ISSUE TITLE
Add Localization

### ISSUE THREAD

**Issue by fstenstrom** [fstenstrom/world-boss-timers#5]
Localization needs to be added for:

* BossData.lua

Currently, the addon doesn't work for non-English, since it triggers on zone-names that are language-dependent.

**Comment by hndr91** [comment]
which one that need localization ? I checked BossData.lue and I still dont understand

**Comment by fstenstrom** [comment]
Currently, the addon checks which zone the user is in to determine if a kill should be registered. For instance "Valley of the Four Winds". On for instance Italian servers this is instead "Valle dei Quattro Venti" which makes the string comparison fail for the function 'IsBossZone'. This is easily fixable by using mapIds, but I haven't checked if there are other problems such as boss names being different. I will check later today.

The realm names and boss names are stored as strings in BossData.lua.

**Comment by fstenstrom** [comment]
Fixed in https://github.com/fstenstrom/world-boss-timers/commit/2468f8352161f54ba5743a40aaac1f67d74cf884

Localization of names in GUI still exists, but is separate issue. See: https://github.com/fstenstrom/world-boss-timers/issues/6
