### ISSUE TITLE
Test.lua file is empty; causes error in WoW

### ISSUE THREAD

**Issue by KyrosKrane** [fstenstrom/world-boss-timers#60]
Just updated to v1.9.

The Test.lua file is completely empty in the packaged addon. This causes WoW to spit out an error complaining about an empty file. The error is visible if you use BugSack or a similar error catching addon.

The easiest fix is to add the do-not-package directive within the TOC file to exclude the Test.lua file from the file list, or else to put any statement in the Test.lua file outside the do-not-package directives.

**Comment by fstenstrom** [comment]
Thanks. That's quite ironic given it's the test file... Applied fix in 649284fc4879c122e97002c82fbd76d49a21878a and e6d82b802872792a43a9c04ef9f7bf6922b1a1a8. Realized I messed up the syntax on first commit right after pushing it... v1.9.2 should be up any moment.

I'll run tests on packaged version for next release.
