### ISSUE TITLE
Rustfeather max time is incorrect

### ISSUE THREAD

**Issue by Gaviin1242** [fstenstrom/world-boss-timers#66]
After a few weeks of farming Rustfeather across 11 toons (on the same server) sequentially, I can say with relative certainty that his respawn timer is 15-30 minutes, not 15-45 as this addon says.

**Comment by fstenstrom** [comment]
Thanks. There does not seem to be any "offical" timers and wowhead comments are disagreeing. I agree that it's probably not 45 min, and 30 min is more in line with what I've encountered as well. I've changed it to 30 min in 541c680c66d7ad433a8a611f3bd968024c86f17f. If it's incorrect I'll "hopefully" get some angry reports.
