### ISSUE TITLE
is it possible to use map id as key

### ISSUE THREAD

**Issue by XiaoPengCn** [fstenstrom/world-boss-timers#76]
you know, There are always many servers sharing a plane

**Comment by XiaoPengCn** [comment]
I am not very good at English, so I put this wrong, you can check out this [wa]("https://wago.io/lzLYg-WaJ") for this **map id** is what I mentioned about

**Comment by fstenstrom** [comment]
In English there are mainly two concepts:

1. Connected realms (servers): WBT supports this already via Util.GetConnectedRealms()
2. Cross-realm: WBT does not support this due to elevated risk of giving incorrect timers when people are grouping

--

What is it you want to use map id as key for? Today it's only used to check if you're in the same zone as a boss.

**Comment by XiaoPengCn** [comment]
Sorry, not map id, should be `zone_uid`
---
a lot of servers shared a same zone, so if my two different characters in same map with same zone_uid, the timer should be shared.

**Comment by XiaoPengCn** [comment]
then the key will look like: `PVE:{zone_uid}:{boss}`

**Comment by fstenstrom** [comment]
With what API do you get zone_uid?

**Comment by XiaoPengCn** [comment]
I dont know the specific API :( , but i got this wa to display current zone_uid in my screen, It's start with some chinese, means `you can hover a npc to display current zone_id（we call it 位面）`
```
!WA:2!TF1ZRTXXx846db2uOjIIjqdKTQ0ujI(AItbtPqivsETJnYsQRwfN8fAxpA3zLMKvZUmZSYw(qjFv)cXxAd1hc0cbc6yON0LMs)2Ms)lyj0)ccoPjxZTERVzxjvf5n0(fCPx6CzFV3mZ79zE)y23mZYPANYoL9UVdZlq4sOywL6gLwTSMULNRhBTzHXaBc33f11aVTyW(F)N9S70F1LE)32QVvax41wk2)SobulbXJMjRIkmyyraJQIcyitmTZ8)7kL1mRV6skyQnRBfhhowCPp4I1nocm8FZjSGPJhRnsy6BkiTXM2DPO2eRw(h)3TwDFBKaRJ7GPIhHcaPibXAdITOvH8aldfbf(I6CbIjukqOeXz2Z2ZmwhB2i(RF1dGp1lOM(z)V7(K7EZN9v3A)F4bpE39E6dUzMNS7T)LEF7JV53LD)7FJ9V)9kxTii6j34Ep9Z)MhFRBpYPKUHdykElLEcgPztmJx(mSHK7EIE2G1Kal1cpIh0ic(vzyhY261QQvQuFBCJahhJU(y2L0kvD56LkiaMWudIXRze3XgX1IyJ1LojBDWhH5kHhRFrV2nqc1sEnhBIAGojBpWSy(AgM1mYRB8OyfS0q44)FMk456zHCvhHwWLCU5xyIjWB7tINYamom9kyHKktw1ZoExtMfmswUP2AovblahLseqJWA4PJXm3)lxrVs9QMRvbYfxkNAmxjTLnYPwTu(RQPBwQYkRwEmNwzdn9vlVI5gv0lbBOC(11mH5mGWA5vnmZV0ss9uV6ssrRxPEnTkxg2NCYXkbCoROzyw8s5lVIC1rzfd5mlRTHzEDT8HP2(O3zShlcU5urSMlmPZlaY4Icx5u3bZ8YPYXSoyMjXoNkHcPLulCeZoEuSzGKI6BfjH7J2IkfnL6IyjoQrwu9cqIAIWlTQOfo29lhq1K61ZP2bSQQpIW4zkAwgYwQ6cLqZdrUXm8mzZQA7nENYXHXXasq4cguFtezs)VsdyzE6iBwh0)kqzx2xWQWHCSHv)e4GcRTlMLwfrTNEgSyQd8OrsL2Jq5bw8We1O0XjLdPMkjrFyFVHYldiyxo(fI5twwKwfcUtpLSgzkxYFFOnXQWPqNmGcaswbLSssSMnzLKUTxah7bPOPtwxjwO)s0f8VJMq61yf9p1u)Lwtbimb9FbvkXncnh6PXVG1pqQmDY7FBg7Zh5AZiDyzhDHC0Khid6qpelntwLeJNjed))m6(NoYMuuDKVA03)Wi5HDaCsqbY0TAHTUE4XE(WMhh1OZM94(yx3vT5kfKoLg(rEP9cOd7rBUWuVISB3Rf939o4ZJOD9pbkI2iEjR7zJ)6J4)gj2XAmr4PFoHkWmkY9YqlGGHR4FQewV1cdPkqbpDYl58J05IfC8Oc)JVmJSJ6hgGSHJes1WOp0MNoUPSDxLcUEi7l3dUb0Kt2b3ApjLSXkwlDlxeNpNE7axbrPa4hSMl8IabSoGyUWf3SN0a1a(t)qElKT3wxjUn9z7ZI0VSV0ccaC7XXUov9GZyJcvmmQSU)B9Y7F3NHTisFWS(NK0K6XWv8JAoxtENSgJ5X4B23YJAtIeRmakoA5XI1FXO26yxd6xL40TG8FB9fEwDIDRNCgZVinXUrCcXquF1yuFQJmWHbxjwtiDuZ(8yTUSuK8G0OwrDnTYSTh(uKF8t)vVq4PinaK4qAQCEiVFq3S1xlZAT369S2(HWZmG9pe7kdITvXO3inZmZmBFOfBSD0tq(VV6EikPDug3IHV2YHNkCXFcJ4sOGPnfTo6dh1qCuvjJJLhFEp5AKydI1TreA0gd)OJg(XHMHBcKV(0s6TLhZEdgYV3gdjsX1F35p38lMQZpFLF7p
```

**Comment by fstenstrom** [comment]
I won't load that weak aura now, but I assume it will return the same as `C_Map.GetBestMapForUnit("player")`.

So the reason it has not been enabled PVE:{boss_id} but rather ConnectedRealm:{boss_id} is that if you are in a zone with low amount of players, then Blizzard can decide to merge it with some other servers (this is called CrossRealm). It's not possible to use the API to determine what servers are part of the CrossRealm-zone, so if you log in on another server, which is not connected to your previous one, then it's possible that you may, or may not, get on the same zone. To keep the addon conservative and avoid false positives, the timer will therefore not show.

Today you can show it, but without getting a warning, by using this option:
![image](https://user-images.githubusercontent.com/39462040/148186470-3a47b46e-2448-40a2-bc62-2cbaca55b797.png)

**Comment by XiaoPengCn** [comment]
Thanks a lot! I will try and see if it worked as I expected.
(but two different set of `CrossRealm` may also in same zone.)
