### ISSUE TITLE
Only show GUI in boss zones doesn't work. 

### ISSUE THREAD

**Issue by olioster** [fstenstrom/world-boss-timers#91]
Even with this option checked in the options menu, I still have to use /wbt toggle to get the window to display when I enter, say, Valley of the Four Winds.

**Comment by fstenstrom** [comment]
Seems to work for me with these options set:

- `Show GUI`: enabled
- `Only show GUI in boss zones`: enabled

If you have `Show GUI` disabled, the window will never show.

**Comment by olioster** [comment]
Sorry, I misunderstood how it worked.
