### ISSUE TITLE
WBT does not register kills on bosses

### ISSUE THREAD

**Issue by drpepin** [fstenstrom/world-boss-timers#94]
Hello, first of all thank you for your work. I've been farming MoP world bosses and WBT doesn't seem to register the bosses deaths, even if I tag them. In order for it to register I have to "check" Show timer for other shards, and even then the timer is impossible to share.

**Comment by fstenstrom** [comment]
I could reproduce it on Galleon. Seems like issue is that Galleon is classified as a "Vehicle" and not a "Creature". Will check the others as well.

**Comment by fstenstrom** [comment]
Tested Sha and Oondasta as well. Seems to work. Version v1.11.2 should soon be available. If issue persists please reopen, and thanks for report in first place.
